PURPOSE = 'What is your research about?'
SOCIAL_CONTEXT = 'What is the social and historical context of the inequality of social issues your work might affect?'
MOTIVE = 'How do you personally benefit from this project?'
WHO_HARM = 'If this research is not done carefully, who might it harm?'
WORST_CASE = 'What is the worst thing that could happen to someone because of this model?'
